version: '3.5'

services:
  db_reserve:
    container_name: postgres_container
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=db_reserve
      - PGDATA=/data/postgres
    image: postgres
    restart: unless-stopped


