spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/db_reserve
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: changelogs/changelog.xml
    enabled: true

  jpa:
    show-sql: false

  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all


server:
  port: 8088
  servlet:
    context-path: /app/v1

jwt:
  token:
    secret: R988574e26654231S54512148eR24517969633V25e524SENLA
    expired: 600000

