spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/db_reserve
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: changelogs/changelog.xml

  server:
    port: 8088
    servlet:
      context-path: /app/v1

packages-to-scan: org.senla.komar.spring

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  token:
    secret: R988574e26654231S54512148eR24517969633V25e524SENLA
    expired: 600000


