spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/db_reserve
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: changelogs/changelog.xml

  jpa:
    show-sql: false


server:
  port: 8088
  servlet:
    context-path: /app/v1

jwt:
  token:
    secret: R988574e26654231S54512148eR24517969633V25e524SENLA
    expired: 600000

